"""empty message

Revision ID: adcffc987acb
Revises: 160b5b9bc979
Create Date: 2021-06-18 21:43:04.512069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcffc987acb'
down_revision = '160b5b9bc979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img')
    # ### end Alembic commands ###
